apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: porg-app
  namespace: porg-ns
spec:
  tls:
    - hosts:
      - www.porg.aahyeehaah.com
      secretName: porg-aahyeehaah-tls
  rules:
  - host: www.porg.aahyeehaah.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: porg-service
            port: 
             number: 80
